# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /PROJET_APP_EMPLOI_NICOLAS

RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]